### ISSUE TITLE
how to repeat your expriments?

### ISSUE THREAD

**Issue by robotzheng** [benedekrozemberczki/CapsGNN#1]
Enumerating feature and target values.

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 60/60 [00:00<00:00, 14754.82it/s]

Training started.

Epochs: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:05<00:00,  1.90it/s]
CapsGNN (Loss=0.7279): 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.92it/s]

Scoring.

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 128.47it/s]

Accuracy: 0.3333

Accuracy is too small

**Comment by benedekrozemberczki** [comment]
This is a subsample of a synthetic dataset. Github limits the number of files You can upload.
