### ISSUE TITLE
std = gain / math.sqrt(fan)   ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by dtzfast** [benedekrozemberczki/CapsGNN#17]
std = gain / math.sqrt(fan)   ZeroDivisionError: float division by zero  
Process finished with exit code 1
what's wrong?who meet the problem.

**Comment by frallisland** [comment]
Do you solve the problem?Maybe this [link](https://ask.csdn.net/questions/3241028)

**Comment by hesilan-1** [comment]
> std = gain / math.sqrt(fan) ZeroDivisionError: float division by zero Process finished with exit code 1 what's wrong?who meet the problem.

do you solute this problem?I meet it too!

**Comment by Mr-Lv-BUU** [comment]
I also meet it.
