### ISSUE TITLE
Something about reshape

### ISSUE THREAD

**Issue by yanx27** [benedekrozemberczki/CapsGNN#5]
Hi @benedekrozemberczki ! Thank you for your work!

I have a question at line 61 and 62 of `CapsGNN/src/capsgnn.py`

> hidden_representations = torch.cat(tuple(hidden_representations))
hidden_representations = hidden_representations.view(1, self.args.gcn_layers, self.args.gcn_filters,-1)

Why  you directly reshape L*N,D to 1,L,D,N instead of using permutation after reshape, e.g
> hidden_representations = hidden_representations.view(1, self.args.gcn_layers, -1,self.args.gcn_filters).permute(0,1,3,2)

Thank you for your help!

**Comment by benedekrozemberczki** [comment]
Which line would you replace?

**Comment by yanx27** [comment]
line 62

**Comment by hujilin1229** [comment]
Hi,

First of all, thanks for your implementation of this paper. After examining your code, I also have a similar question that you did view() without permutation. In addition to the above code mentioned by @yanx27 , just two lines below, 
`first_capsule_output = first_capsule_output.view(-1,self.args.gcn_layers* self.args.capsule_dimensions)`
In this case, I have checked that 'first_capsule_output' should have a shape of (1, gcn_layers, capsule_dimensions*num_nodes). However, your implementation confuses me a lot. Can you elaborate a little about it?

Kind Regards,
Jilin

**Comment by zhangxin9988** [comment]
hidden_representations = hidden_representations.view(1, self.args.gcn_layers, -1,self.args.gcn_filters).permute(0,1,3,2)
I agree with you!

> https://github.com/benedekrozemberczki/CapsGNN/issues/5#issue-437013520
